name: Deploy Documentation (Manual)

# This workflow deploys documentation to Azure Static Web Apps
# - Main branch: Deploys to production (https://docs.accelergreat.net)
# - Other branches: Automatically creates preview environments

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    name: Deploy Documentation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Generate version
      id: version
      run: |
        # Read base version from version.json
        BASE_VERSION=$(jq -r '.version' version.json)
        
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          # For main branch, use the base version
          VERSION="${BASE_VERSION}"
        else
          # For non-main branches, add pre-release suffix
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          VERSION="${BASE_VERSION}-beta.${SHORT_SHA}"
        fi
        
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Deploying docs with version: ${VERSION}"
        
        # Replace version tokens in all files
        echo "Replacing version tokens in all files..."
        find . -name "*.json" -o -name "*.md" | while read file; do
          if grep -q "~(version)~" "$file"; then
            echo "Replacing version in: $file"
            sed -i "s/~(version)~/${VERSION}/g" "$file"
          fi
        done

    - name: Install dependencies
      run: npm install

    - name: Build documentation site
      run: npm run build

    - name: Verify documentation build output
      run: |
        echo "Checking _site directory contents:"
        if [ -d "_site" ]; then
          echo "_site directory exists"
          echo "Contents of _site:"
          ls -la _site/
          
          # Check if index.html exists at root
          if [ -f "_site/index.html" ]; then
            echo "✓ index.html found in _site root"
          else
            echo "✗ index.html NOT found in _site root"
            exit 1
          fi
          
          # Check if assets were copied
          echo "Checking for assets:"
          ls -la _site/accelergreat-logo.svg _site/favicon.ico _site/styles/main.css || true
        else
          echo "ERROR: _site directory does not exist!"
          exit 1
        fi

    - name: Determine deployment environment
      id: deployment_env
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "environment=Production" >> $GITHUB_OUTPUT
          echo "Deploying to Production"
        else
          echo "environment=Preview" >> $GITHUB_OUTPUT
          echo "Deploying to Preview environment for branch: ${GITHUB_REF#refs/heads/}"
        fi

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "_site"
        skip_app_build: true
        production_branch: "main"