name: Deploy to Production (Auto)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  BUILD_CONFIGURATION: Release

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy Docs then NuGet to Production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
          9.0.x

    - name: Generate version
      id: version
      run: |
        # Read version from version.json
        VERSION=$(jq -r '.version' version.json)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        
        # Replace version tokens in all files (matching original Azure DevOps pipeline)
        echo "Replacing version tokens in all files..."
        find . -name "*.json" -o -name "*.md" -o -name "*.props" | while read file; do
          if grep -q "~(version)~" "$file"; then
            echo "Replacing version in: $file"
            sed -i "s/~(version)~/${VERSION}/g" "$file"
          fi
        done

    - name: Restore dependencies
      run: dotnet restore Accelergreat.sln

    - name: Build solution
      run: dotnet build Accelergreat.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Pack NuGet packages
      run: |
        # Create output directory
        mkdir -p ./nuget-packages
        
        echo "Packing NuGet packages..."
        for project in $(find src/ -name "*.csproj" -type f); do
          echo "Packing project: $project"
          dotnet pack "$project" \
            --configuration ${{ env.BUILD_CONFIGURATION }} \
            --output ./nuget-packages \
            -p:PackageVersion=${{ steps.version.outputs.version }} \
            -p:Version=${{ steps.version.outputs.version }} \
            --verbosity normal
        done
        
        echo "Created packages:"
        ls -la ./nuget-packages/

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Setup custom template
      run: |
        echo "Setting up custom Accelergreat template..."
        mkdir -p _exported_templates/accelergreat
        
        # Create a minimal template overlay for branding
        cat > _exported_templates/accelergreat/layout/_master.liquid << 'EOF'
        <!-- This is an overlay template that extends the default template -->
        EOF

    - name: Build documentation
      run: |
        echo "Building documentation with DocFX"
        docfx --warningsAsErrors false
        echo "DocFX build completed"

    - name: Verify documentation build output
      run: |
        echo "Checking _site directory contents:"
        if [ -d "_site" ]; then
          echo "_site directory exists"
          echo "Contents of _site:"
          ls -la _site/
          echo "Searching for all HTML files in _site:"
          find _site -name "*.html" -type f | head -20
          
          # Check if index.html exists at root
          if [ -f "_site/index.html" ]; then
            echo "✓ index.html found in _site root"
          else
            echo "✗ index.html NOT found in _site root"
            echo "All files in _site:"
            find _site -type f
          fi
          
          # Check if logo was copied
          echo "Checking for Accelergreat logo:"
          find _site -name "*accelergreat_icon*" -type f
        else
          echo "ERROR: _site directory does not exist!"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "_site"
        skip_app_build: true
        production_branch: "main"

    - name: Deploy to NuGet
      run: |
        echo "Deploying NuGet packages..."
        dotnet nuget push "./nuget-packages/*.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate

